export const Countries = [
  { country: 'Afghanistan', continent: 'Asia', id: 65544 },
  { country: 'Albania', continent: 'Europe', id: 56201 },
  { country: 'Algeria', continent: 'Africa', id: 67675 },
  { country: 'American Samoa', continent: 'Oceania', id: 28003 },
  { country: 'Andorra', continent: 'Europe', id: 18847 },
  { country: 'Angola', continent: 'Africa', id: 44124 },
  { country: 'Anguilla', continent: 'North America', id: 16871 },
  { country: 'Antarctica', continent: 'Antarctica', id: 62095 },
  { country: 'Antigua and Barbuda', continent: 'North America', id: 73993 },
  { country: 'Argentina', continent: 'South America', id: 97745 },
  { country: 'Armenia', continent: 'Asia', id: 93244 },
  { country: 'Aruba', continent: 'North America', id: 12518 },
  { country: 'Australia', continent: 'Oceania', id: 6868 },
  { country: 'Austria', continent: 'Europe', id: 14182 },
  { country: 'Azerbaijan', continent: 'Asia', id: 28341 },
  { country: 'Bahamas', continent: 'North America', id: 47121 },
  { country: 'Bahrain', continent: 'Asia', id: 22237 },
  { country: 'Bangladesh', continent: 'Asia', id: 19438 },
  { country: 'Barbados', continent: 'North America', id: 88645 },
  { country: 'Belarus', continent: 'Europe', id: 85909 },
  { country: 'Belgium', continent: 'Europe', id: 42179 },
  { country: 'Belize', continent: 'North America', id: 17047 },
  { country: 'Benin', continent: 'Africa', id: 6311 },
  { country: 'Bermuda', continent: 'North America', id: 28861 },
  { country: 'Bhutan', continent: 'Asia', id: 74225 },
  { country: 'Bolivia', continent: 'South America', id: 46775 },
  { country: 'Bosnia and Herzegovina', continent: 'Europe', id: 91902 },
  { country: 'Botswana', continent: 'Africa', id: 48235 },
  { country: 'Bouvet Island', continent: 'Antarctica', id: 28576 },
  { country: 'Brazil', continent: 'South America', id: 64248 },
  { country: 'British Indian Ocean Territory', continent: 'Africa', id: 7463 },
  { country: 'Brunei', continent: 'Asia', id: 45565 },
  { country: 'Bulgaria', continent: 'Europe', id: 69669 },
  { country: 'Burkina Faso', continent: 'Africa', id: 65868 },
  { country: 'Burundi', continent: 'Africa', id: 16536 },
  { country: 'Cambodia', continent: 'Asia', id: 81694 },
  { country: 'Cameroon', continent: 'Africa', id: 84793 },
  { country: 'Canada', continent: 'North America', id: 6418 },
  { country: 'Cape Verde', continent: 'Africa', id: 69385 },
  { country: 'Cayman Islands', continent: 'North America', id: 95972 },
  { country: 'Central African Republic', continent: 'Africa', id: 45364 },
  { country: 'Chad', continent: 'Africa', id: 90351 },
  { country: 'Chile', continent: 'South America', id: 84107 },
  { country: 'China', continent: 'Asia', id: 72917 },
  { country: 'Christmas Island', continent: 'Oceania', id: 55177 },
  { country: 'Cocos (Keeling) Islands', continent: 'Oceania', id: 71794 },
  { country: 'Colombia', continent: 'South America', id: 3966 },
  { country: 'Comoros', continent: 'Africa', id: 69696 },
  { country: 'Congo', continent: 'Africa', id: 89974 },
  { country: 'Cook Islands', continent: 'Oceania', id: 81386 },
  { country: 'Costa Rica', continent: 'North America', id: 43717 },
  { country: 'Croatia', continent: 'Europe', id: 56179 },
  { country: 'Cuba', continent: 'North America', id: 62420 },
  { country: 'Cyprus', continent: 'Asia', id: 10678 },
  { country: 'Czech Republic', continent: 'Europe', id: 58762 },
  { country: 'Denmark', continent: 'Europe', id: 93561 },
  { country: 'Djibouti', continent: 'Africa', id: 43384 },
  { country: 'Dominica', continent: 'North America', id: 65627 },
  { country: 'Dominican Republic', continent: 'North America', id: 43508 },
  { country: 'East Timor', continent: 'Asia', id: 12764 },
  { country: 'Ecuador', continent: 'South America', id: 9585 },
  { country: 'Egypt', continent: 'Africa', id: 88722 },
  { country: 'El Salvador', continent: 'North America', id: 97107 },
  { country: 'England', continent: 'Europe', id: 48766 },
  { country: 'Equatorial Guinea', continent: 'Africa', id: 67062 },
  { country: 'Eritrea', continent: 'Africa', id: 97692 },
  { country: 'Estonia', continent: 'Europe', id: 46734 },
  { country: 'Ethiopia', continent: 'Africa', id: 88755 },
  { country: 'Falkland Islands', continent: 'South America', id: 45124 },
  { country: 'Faroe Islands', continent: 'Europe', id: 33877 },
  { country: 'Fiji Islands', continent: 'Oceania', id: 78129 },
  { country: 'Finland', continent: 'Europe', id: 98053 },
  { country: 'France', continent: 'Europe', id: 84383 },
  { country: 'French Guiana', continent: 'South America', id: 75863 },
  { country: 'French Polynesia', continent: 'Oceania', id: 45074 },
  { country: 'French Southern territories', continent: 'Antarctica', id: 61499 },
  { country: 'Gabon', continent: 'Africa', id: 96789 },
  { country: 'Gambia', continent: 'Africa', id: 68485 },
  { country: 'Georgia', continent: 'Asia', id: 99639 },
  { country: 'Germany', continent: 'Europe', id: 58062 },
  { country: 'Ghana', continent: 'Africa', id: 26787 },
  { country: 'Gibraltar', continent: 'Europe', id: 83136 },
  { country: 'Greece', continent: 'Europe', id: 74039 },
  { country: 'Greenland', continent: 'North America', id: 4517 },
  { country: 'Grenada', continent: 'North America', id: 24525 },
  { country: 'Guadeloupe', continent: 'North America', id: 17567 },
  { country: 'Guam', continent: 'Oceania', id: 92835 },
  { country: 'Guatemala', continent: 'North America', id: 88027 },
  { country: 'Guinea', continent: 'Africa', id: 57154 },
  { country: 'Guinea-Bissau', continent: 'Africa', id: 72911 },
  { country: 'Guyana', continent: 'South America', id: 68650 },
  { country: 'Haiti', continent: 'North America', id: 73731 },
  { country: 'Heard Island and McDonald Islands', continent: 'Antarctica', id: 75858 },
  { country: 'Holy See (Vatican City State)', continent: 'Europe', id: 85731 },
  { country: 'Honduras', continent: 'North America', id: 99575 },
  { country: 'Hong Kong', continent: 'Asia', id: 34207 },
  { country: 'Hungary', continent: 'Europe', id: 80481 },
  { country: 'Iceland', continent: 'Europe', id: 24580 },
  { country: 'India', continent: 'Asia', id: 9622 },
  { country: 'Indonesia', continent: 'Asia', id: 73366 },
  { country: 'Iran', continent: 'Asia', id: 94992 },
  { country: 'Iraq', continent: 'Asia', id: 51372 },
  { country: 'Ireland', continent: 'Europe', id: 2355 },
  { country: 'Israel', continent: 'Asia', id: 67656 },
  { country: 'Italy', continent: 'Europe', id: 29220 },
  { country: 'Ivory Coast', continent: 'Africa', id: 81087 },
  { country: 'Jamaica', continent: 'North America', id: 25546 },
  { country: 'Japan', continent: 'Asia', id: 69411 },
  { country: 'Jordan', continent: 'Asia', id: 18894 },
  { country: 'Kazakhstan', continent: 'Asia', id: 69758 },
  { country: 'Kenya', continent: 'Africa', id: 59906 },
  { country: 'Kiribati', continent: 'Oceania', id: 37160 },
  { country: 'Kuwait', continent: 'Asia', id: 68967 },
  { country: 'Kyrgyzstan', continent: 'Asia', id: 91727 },
  { country: 'Laos', continent: 'Asia', id: 27597 },
  { country: 'Latvia', continent: 'Europe', id: 53166 },
  { country: 'Lebanon', continent: 'Asia', id: 85418 },
  { country: 'Lesotho', continent: 'Africa', id: 35463 },
  { country: 'Liberia', continent: 'Africa', id: 75159 },
  { country: 'Libyan Arab Jamahiriya', continent: 'Africa', id: 19123 },
  { country: 'Liechtenstein', continent: 'Europe', id: 98709 },
  { country: 'Lithuania', continent: 'Europe', id: 15330 },
  { country: 'Luxembourg', continent: 'Europe', id: 80551 },
  { country: 'Macao', continent: 'Asia', id: 18857 },
  { country: 'North Macedonia', continent: 'Europe', id: 30506 },
  { country: 'Madagascar', continent: 'Africa', id: 63783 },
  { country: 'Malawi', continent: 'Africa', id: 57653 },
  { country: 'Malaysia', continent: 'Asia', id: 64819 },
  { country: 'Maldives', continent: 'Asia', id: 28548 },
  { country: 'Mali', continent: 'Africa', id: 70355 },
  { country: 'Malta', continent: 'Europe', id: 8740 },
  { country: 'Marshall Islands', continent: 'Oceania', id: 27004 },
  { country: 'Martinique', continent: 'North America', id: 54014 },
  { country: 'Mauritania', continent: 'Africa', id: 59954 },
  { country: 'Mauritius', continent: 'Africa', id: 27266 },
  { country: 'Mayotte', continent: 'Africa', id: 76776 },
  { country: 'Mexico', continent: 'North America', id: 90118 },
  { country: 'Micronesia, Federated States of', continent: 'Oceania', id: 97975 },
  { country: 'Moldova', continent: 'Europe', id: 19504 },
  { country: 'Monaco', continent: 'Europe', id: 26559 },
  { country: 'Mongolia', continent: 'Asia', id: 88259 },
  { country: 'Montenegro', continent: 'Europe', id: 98774 },
  { country: 'Montserrat', continent: 'North America', id: 5748 },
  { country: 'Morocco', continent: 'Africa', id: 88618 },
  { country: 'Mozambique', continent: 'Africa', id: 56081 },
  { country: 'Myanmar', continent: 'Asia', id: 35377 },
  { country: 'Namibia', continent: 'Africa', id: 26490 },
  { country: 'Nauru', continent: 'Oceania', id: 14526 },
  { country: 'Nepal', continent: 'Asia', id: 30482 },
  { country: 'Netherlands', continent: 'Europe', id: 38688 },
  { country: 'Netherlands Antilles', continent: 'North America', id: 77967 },
  { country: 'New Caledonia', continent: 'Oceania', id: 84423 },
  { country: 'New Zealand', continent: 'Oceania', id: 91369 },
  { country: 'Nicaragua', continent: 'North America', id: 96547 },
  { country: 'Niger', continent: 'Africa', id: 1923 },
  { country: 'Nigeria', continent: 'Africa', id: 92957 },
  { country: 'Niue', continent: 'Oceania', id: 30548 },
  { country: 'Norfolk Island', continent: 'Oceania', id: 4798 },
  { country: 'North Korea', continent: 'Asia', id: 57293 },
  { country: 'Northern Ireland', continent: 'Europe', id: 79532 },
  { country: 'Northern Mariana Islands', continent: 'Oceania', id: 22542 },
  { country: 'Norway', continent: 'Europe', id: 99773 },
  { country: 'Oman', continent: 'Asia', id: 49895 },
  { country: 'Pakistan', continent: 'Asia', id: 51797 },
  { country: 'Palau', continent: 'Oceania', id: 26464 },
  { country: 'Palestine', continent: 'Asia', id: 2869 },
  { country: 'Panama', continent: 'North America', id: 97994 },
  { country: 'Papua New Guinea', continent: 'Oceania', id: 36517 },
  { country: 'Paraguay', continent: 'South America', id: 6959 },
  { country: 'Peru', continent: 'South America', id: 87121 },
  { country: 'Philippines', continent: 'Asia', id: 23298 },
  { country: 'Pitcairn', continent: 'Oceania', id: 54045 },
  { country: 'Poland', continent: 'Europe', id: 52974 },
  { country: 'Portugal', continent: 'Europe', id: 92196 },
  { country: 'Puerto Rico', continent: 'North America', id: 29533 },
  { country: 'Qatar', continent: 'Asia', id: 17604 },
  { country: 'Reunion', continent: 'Africa', id: 31989 },
  { country: 'Romania', continent: 'Europe', id: 3413 },
  { country: 'Russian Federation', continent: 'Europe', id: 75723 },
  { country: 'Rwanda', continent: 'Africa', id: 98530 },
  { country: 'Saint Helena', continent: 'Africa', id: 33983 },
  { country: 'Saint Kitts and Nevis', continent: 'North America', id: 45316 },
  { country: 'Saint Lucia', continent: 'North America', id: 89362 },
  { country: 'Saint Pierre and Miquelon', continent: 'North America', id: 12900 },
  { country: 'Saint Vincent and the Grenadines', continent: 'North America', id: 12836 },
  { country: 'Samoa', continent: 'Oceania', id: 25870 },
  { country: 'San Marino', continent: 'Europe', id: 11800 },
  { country: 'Sao Tome and Principe', continent: 'Africa', id: 88998 },
  { country: 'Saudi Arabia', continent: 'Asia', id: 77499 },
  { country: 'Scotland', continent: 'Europe', id: 57049 },
  { country: 'Senegal', continent: 'Africa', id: 67993 },
  { country: 'Seychelles', continent: 'Africa', id: 18759 },
  { country: 'Sierra Leone', continent: 'Africa', id: 3871 },
  { country: 'Singapore', continent: 'Asia', id: 68299 },
  { country: 'Slovakia', continent: 'Europe', id: 62900 },
  { country: 'Slovenia', continent: 'Europe', id: 85989 },
  { country: 'Solomon Islands', continent: 'Oceania', id: 26124 },
  { country: 'Somalia', continent: 'Africa', id: 54482 },
  { country: 'South Africa', continent: 'Africa', id: 94698 },
  { country: 'South Georgia and the South Sandwich Islands', continent: 'Antarctica', id: 4290 },
  { country: 'South Korea', continent: 'Asia', id: 71711 },
  { country: 'South Sudan', continent: 'Africa', id: 7086 },
  { country: 'Spain', continent: 'Europe', id: 79290 },
  { country: 'Sri Lanka', continent: 'Asia', id: 6011 },
  { country: 'Sudan', continent: 'Africa', id: 48233 },
  { country: 'Suriname', continent: 'South America', id: 21427 },
  { country: 'Svalbard and Jan Mayen', continent: 'Europe', id: 7750 },
  { country: 'Swaziland', continent: 'Africa', id: 5811 },
  { country: 'Sweden', continent: 'Europe', id: 54863 },
  { country: 'Switzerland', continent: 'Europe', id: 54540 },
  { country: 'Syria', continent: 'Asia', id: 74616 },
  { country: 'Tajikistan', continent: 'Asia', id: 64335 },
  { country: 'Tanzania', continent: 'Africa', id: 9991 },
  { country: 'Thailand', continent: 'Asia', id: 38711 },
  { country: 'The Democratic Republic of Congo', continent: 'Africa', id: 53777 },
  { country: 'Togo', continent: 'Africa', id: 45783 },
  { country: 'Tokelau', continent: 'Oceania', id: 6725 },
  { country: 'Tonga', continent: 'Oceania', id: 52257 },
  { country: 'Trinidad and Tobago', continent: 'North America', id: 44640 },
  { country: 'Tunisia', continent: 'Africa', id: 91420 },
  { country: 'Turkey', continent: 'Asia', id: 34419 },
  { country: 'Turkmenistan', continent: 'Asia', id: 35845 },
  { country: 'Turks and Caicos Islands', continent: 'North America', id: 34112 },
  { country: 'Tuvalu', continent: 'Oceania', id: 92051 },
  { country: 'Uganda', continent: 'Africa', id: 89126 },
  { country: 'Ukraine', continent: 'Europe', id: 24530 },
  { country: 'United Arab Emirates', continent: 'Asia', id: 67508 },
  { country: 'United Kingdom', continent: 'Europe', id: 5480 },
  { country: 'United States', continent: 'North America', id: 51835 },
  { country: 'United States Minor Outlying Islands', continent: 'Oceania', id: 38399 },
  { country: 'Uruguay', continent: 'South America', id: 7979 },
  { country: 'Uzbekistan', continent: 'Asia', id: 55872 },
  { country: 'Vanuatu', continent: 'Oceania', id: 79923 },
  { country: 'Venezuela', continent: 'South America', id: 75542 },
  { country: 'Vietnam', continent: 'Asia', id: 66044 },
  { country: 'Virgin Islands, British', continent: 'North America', id: 68580 },
  { country: 'Virgin Islands, U.S.', continent: 'North America', id: 31536 },
  { country: 'Wales', continent: 'Europe', id: 44575 },
  { country: 'Wallis and Futuna', continent: 'Oceania', id: 14235 },
  { country: 'Western Sahara', continent: 'Africa', id: 32226 },
  { country: 'Yemen', continent: 'Asia', id: 75450 },
  { country: 'Yugoslavia', continent: 'Europe', id: 8168 },
  { country: 'Zambia', continent: 'Africa', id: 44811 },
  { country: 'Zimbabwe', continent: 'Africa', id: 21968 },
];

export default Countries;
